apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
    - image: node:v5
      name: helloworld
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP  
